import 'package:equatable/equatable.dart';

/// Represents the trigger type for AI message generation.
enum MessageTriggerType {
  dailyFirstOpen,
  postCheckin,
}

/// AI-generated contextual message entity for dashboard display.
///
/// Messages are generated by LLM based on user context (journey stage,
/// escalation timing, weight trends, etc.) to provide empathetic support.
class AIGeneratedMessage extends Equatable {
  /// Unique identifier for the message
  final String id;

  /// User ID who received this message
  final String userId;

  /// The AI-generated message text
  final String message;

  /// Snapshot of the context used to generate this message (JSONB)
  /// Contains: user_context, health_data
  final Map<String, dynamic>? contextSnapshot;

  /// When the message was generated
  final DateTime generatedAt;

  /// What triggered the message generation
  final MessageTriggerType triggerType;

  const AIGeneratedMessage({
    required this.id,
    required this.userId,
    required this.message,
    this.contextSnapshot,
    required this.generatedAt,
    required this.triggerType,
  });

  AIGeneratedMessage copyWith({
    String? id,
    String? userId,
    String? message,
    Map<String, dynamic>? contextSnapshot,
    DateTime? generatedAt,
    MessageTriggerType? triggerType,
  }) {
    return AIGeneratedMessage(
      id: id ?? this.id,
      userId: userId ?? this.userId,
      message: message ?? this.message,
      contextSnapshot: contextSnapshot ?? this.contextSnapshot,
      generatedAt: generatedAt ?? this.generatedAt,
      triggerType: triggerType ?? this.triggerType,
    );
  }

  @override
  List<Object?> get props => [
        id,
        userId,
        message,
        contextSnapshot,
        generatedAt,
        triggerType,
      ];

  @override
  String toString() =>
      'AIGeneratedMessage(id: $id, userId: $userId, triggerType: $triggerType, generatedAt: $generatedAt)';
}
