-- ============================================
-- AI Generated Messages Table
-- 2025-12-07
-- ============================================
-- This table stores AI-generated contextual messages for dashboard display.
-- Messages are generated by LLM via Edge Function based on user context,
-- health data, and recent messages for tone consistency.

-- ============================================
-- 1. Create ai_generated_messages table
-- ============================================
CREATE TABLE IF NOT EXISTS public.ai_generated_messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id TEXT NOT NULL REFERENCES public.users(id) ON DELETE CASCADE,
  message TEXT NOT NULL,
  context_snapshot JSONB,
  generated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  trigger_type TEXT NOT NULL CHECK (trigger_type IN ('daily_first_open', 'post_checkin'))
);

-- ============================================
-- 2. Create indexes for performance
-- ============================================
-- Index for fetching recent messages (latest messages first)
CREATE INDEX IF NOT EXISTS idx_ai_messages_user_date
  ON public.ai_generated_messages(user_id, generated_at DESC);

-- ============================================
-- 3. Enable Row Level Security (RLS)
-- ============================================
ALTER TABLE public.ai_generated_messages ENABLE ROW LEVEL SECURITY;

-- Users can only read their own messages
CREATE POLICY "Users can read own messages"
  ON public.ai_generated_messages FOR SELECT
  USING (auth.uid()::TEXT = user_id);

-- Note: INSERT is performed by Edge Function with service role
-- No INSERT policy needed for regular users

-- ============================================
-- Completed
-- ============================================
